apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nessus-secrets.fullname" . }}
  labels:
    {{- include "nessus-secrets.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "nessus-secrets.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nessus-secrets.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "tenable/nessus:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8834
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: ACTIVATION_CODE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: activation_code
                  optional: true
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: username
                  optional: true
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: password
                  optional: true
          volumeMounts:
          {{- if .Values.persistence.enabled }}
            - name: nessus-data
              mountPath: /opt/nessus/var/nessus
              subPath: var
            - name: nessus-data
              mountPath: /opt/nessus/etc/nessus
              subPath: etc
          {{- end }}
          {{- if .Values.serverCert.enabled }}
            - name: nessus-server-cert
              mountPath: "/tls"
              readOnly: true
          {{- end }}
          {{- if .Values.serverCert.enabled }}
          lifecycle:
            preStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - |
                    KEY="/tls/tls.key"
                    CRT="/tls/tls.crt"
                    if [ -f "$KEY" ] && [ -f "$CRT" ]; then
                      echo "Importing Nessus server cert..."
                      /opt/nessus/sbin/nessuscli import-certs --serverkey="$KEY" --servercert="$CRT" || true
                    else
                      echo "TLS files not present at $KEY / $CRT, skipping import"
                    fi
          {{- end }}
      volumes:
      {{- if .Values.persistence.enabled }}
        - name: nessus-data
          persistentVolumeClaim:
            claimName: {{ include "nessus-secrets.fullname" . }}
      {{- end }}
      {{- if .Values.serverCert.enabled }}
        - name: nessus-server-cert
          secret:
            secretName: {{ .Values.serverCert.secretName }}
            optional: true
      {{- end }}
