apiVersion: v1
kind: Secret
metadata:
  name: nessus-credentials
  namespace: nessus
type: Opaque
stringData:
  activation_code: "<your-activation-code>"
  username: "<your-nessus-username>"
  password: "<your-nessus-password>"
