apiVersion: v2
name: nessus-secrets
description: Nessus vulnerability scanner with Secrets and Ingress integration
type: application
version: 0.1.4
appVersion: "latest"
keywords:
  - nessus
  - vulnerability
  - scanner
  - security
home: https://www.tenable.com/products/nessus
sources:
  - https://github.com/timycyip/nessus-kubernetes-secrets
maintainers:
  - name: timycyip
    email: mail@timyip.work
